apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: apache
        image: php:7.4-apache
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /var/www/html
      volumes:
      - name: html-volume
        hostPath:
          path: /path/to/your/public-html
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort