  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: edb-deployment
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: edb
    template:
      metadata:
        labels:
          app: edb
      spec:
        containers:
        - name: edb-container
          image: docker.enterprisedb.com/enterprisedb/edb-as:13
          ports:
          - containerPort: 5444
          env:
          - name: POSTGRES_USER
            value: "admin"
          - name: POSTGRES_PASSWORD
            value: "secretpassword"
          - name: POSTGRES_DB
            value: "demo_db"
          volumeMounts:
          - name: edbdata
            mountPath: /var/lib/postgresql/data
        imagePullSecrets:
        - name: edb-registry-secret
        volumes:
        - name: edbdata
          hostPath:
            path: /path/to/your/edbdata